<a href="https://colab.research.google.com/github/RaviralaLathasri/numpybasics/blob/main/numpybasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
l1=[1,2,3]
array1=np.array(l1)
array1

array([1, 2, 3])

In [2]:
a=np.array([1,2,3,7])
for x in a:
  print(x)

1
2
3
7


In [3]:
#creates a NumPy array with a minimum of 5 dimensions.
a=np.array([1,2,3,4,5,6],ndmin=5)
a

array([[[[[1, 2, 3, 4, 5, 6]]]]])

In [4]:
#concatenate the two arrays
a1=np.array([1,2,3,4])
a2=np.array([53,67,99])
a3=np.concatenate((a1,a2))
print(a3)

[ 1  2  3  4 53 67 99]


In [5]:
#concatenate in 2d
a1=np.array([[1,2,3,4],[21,22,23,24]])
a2=np.array([[53,67,9,9],[45,46,47,48]])
a3=np.concatenate((a1,a2),axis=1)
print(a3)


[[ 1  2  3  4 53 67  9  9]
 [21 22 23 24 45 46 47 48]]


In [6]:
#split
a1=np.array([[1,2,3,4],[21,22,23,24]])
array=np.array_split(a1,1)
print(array)

[array([[ 1,  2,  3,  4],
       [21, 22, 23, 24]])]


In [7]:
#searching
a1=np.array([[1,2,3,4],[21,22,23,4]])
x=np.where(a1==4)
print(x)

(array([0, 1]), array([3, 3]))


In [8]:
#sorting
a=np.array([[1,3,5,6],[8,9,2,5]])
x=np.sort(a)
x

array([[1, 3, 5, 6],
       [2, 5, 8, 9]])

In [9]:
#sorting of alphabets
a=np.array([['raja','latha','sruthi'],['manasa','rosh','sanju']])
x=np.sort(a)
x

array([['latha', 'raja', 'sruthi'],
       ['manasa', 'rosh', 'sanju']], dtype='<U6')

In [10]:
#ndemurate in 1D
a=np.array([11,32,35,4])
for idx,x in np.ndenumerate(a):
  print(idx,x)

(0,) 11
(1,) 32
(2,) 35
(3,) 4


In [11]:
#ndemurate in 2D
a=np.array([[21,23,35],[445,46,43]])
for idx,x in np.ndenumerate(a):
  print(idx,x)

(0, 0) 21
(0, 1) 23
(0, 2) 35
(1, 0) 445
(1, 1) 46
(1, 2) 43


In [12]:
#filters
a=np.array([4,6,8,34])
x=[True,False,False,True]
newarr=a[x]
newarr

array([ 4, 34])

In [13]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [14]:
#boolean
array1=np.array([0,1,2,3])
array2=array1.astype(bool)
array2

array([False,  True,  True,  True])

In [15]:
 #finding the indices of even numbers in a NumPy array.
a1=np.array([1,2,3,4])
a2=np.where(a1%2==0)
print("even",a2)


even (array([1, 3]),)


In [16]:
#view(new addresses allocated)
a1=np.array([1,2,3,4])
a2=a1.view()
a2[3]=5
print(a2)

[1 2 3 5]


In [17]:
#copy(original not effects)
a1=np.array([1,2,3,4])
a2=a1.copy()
a2[3]=5
print(a2)


[1 2 3 5]


In [18]:
#filtering elements from a NumPy array that fall within a specified range (between lb and ub inclusively).

a1 = np.array([1, 2, 3, 4])  # Create a NumPy array
lb = 3  # Lower bound
ub = 5  # Upper bound

a2 = a1[(a1 >= lb) & (a1 <= ub)]  # Filter values within range [3,5]
print(a2)


[3 4]


In [19]:
a1=np.array([1,2,3,4,9,6])
a1.reshape(3,2)


array([[1, 2],
       [3, 4],
       [9, 6]])

In [20]:
a1=np.array([1,2,3,4,9,6])
for x in a1[1:5]:
  print(x)

2
3
4
9


In [21]:
#union
a1=np.array([1,2,3,4])
a2=np.array([1,23,32,14])
a3=np.union1d(a1,a2)
print(a3)

[ 1  2  3  4 14 23 32]


In [22]:
a1=np.array([[1,2,3,4],[21,22,23,4]])

In [23]:
#intersection
a1=np.array([1,2,21,4])
a2=np.array([1,21,32,14])
a3=np.intersect1d(a1,a2)
print(a3)

[ 1 21]


In [24]:
#positions of the intersection
a1=np.array([1,2,21,4])
a2=np.array([1,21,32,14])
a3=np.intersect1d(a1,a2)
print(a3)
position=np.where(a3==a3)
print(position)

[ 1 21]
(array([0, 1]),)


In [25]:
#converting the array into 1d
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.reshape(a,(1,-1,)))
#another method
print(np.ravel(a))

[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [26]:
#swaping 2 colums in 2d
a=np.array([[1,2,3],[4,5,6]])
print(a)
a[:,[0,1]]=a[:,[1,0]]
print(a)

[[1 2 3]
 [4 5 6]]
[[2 1 3]
 [5 4 6]]


In [27]:
#finding the mean,median,sd of array
a=np.array([1,2,3,34,76,81,2])
print("mean of array is:",np.mean(a))
print("median of array:",np.median(a))
print("sd of array:",np.std(a))


mean of array is: 28.428571428571427
median of array: 3.0
sd of array: 33.49565917657793


In [28]:
#percentile of array
a=np.array([12,45,123])
print(np.percentile(a,75))

84.0


In [29]:
#to find the distance b/w array
a=np.array([1,2,3,44])
b=np.array([2,6,77,65])
print(np.linalg.norm(a-b ))

77.03246069028303


In [30]:
a=np.array([1,2,3,4],dtype=bool)
print(a)


[ True  True  True  True]


In [31]:
#place -1 in place of odd numbers
a=np.array([1,2,3,4])
a[a%2==1]=-1
print(a)


[-1  2 -1  4]


In [32]:
#place 1 in place of even numbers
a=np.array([1,2,3,4])
a[a%2==0]=1
print(a)

[1 1 3 1]


In [33]:
#prime numbers
import numpy as np

# Define the array
a = np.array([1, 2, 3, 4, 5, 6, 7])

# Function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Filtering prime numbers from the array
prime_numbers = np.array([num for num in a if is_prime(num)])

# Print the result
print("Prime numbers:", prime_numbers)



Prime numbers: [2 3 5 7]


In [34]:
#converting 1d to 3d
a=np.array([1,2,3,4,5,6,7,8,9])
a2d=a.reshape(-1,3,1)
print(a2d)


[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [35]:
#indexing in 1d array
a=np.array([1,2,3,4,5])
a[1:4]

array([2, 3, 4])

In [36]:
#correlation b/w two arrays
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
c1=a[:,0]
c2=a[:,1]
correlation=np.corrcoef(c1,c2)
print("correlation coefficient between columno and column1:")
print(correlation [0,1])

correlation coefficient between columno and column1:
1.0


In [37]:
#probabilistic sampling
pop=np.array(['A','B','C','D','e'])
prob=np.array([0.1,0.2,0.3,0.2,0.2])
samp_with_rep = np.random.choice(pop,size=4,p=prob,replace=True)
print("sample with replacement:",samp_with_rep)
samp_without_rep=np.random.choice(pop,size=3,p=prob,replace=False)
print("sample without replacement:",samp_without_rep)



sample with replacement: ['e' 'D' 'C' 'B']
sample without replacement: ['A' 'C' 'B']


In [38]:

def moving_average(arr, window_size):
    kernel = np.ones(window_size) / window_size
    moving_avg = np.convolve(arr, kernel, mode='valid')
    return moving_avg

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
window_size = 3
result = moving_average(arr, window_size)
print("Moving average:", result)




Moving average: [2. 3. 4. 5. 6. 7. 8. 9.]


In [39]:
#find the position of missing values
arr=np.array([1,2,np.nan,4,np.nan,6,7,np.nan])
missing_value_positions=np.where(np.isnan(arr))[0]
print("positions of missing values:",missing_value_positions)


positions of missing values: [2 4 7]


In [40]:
#drop rows that contain the missing value
sample_data=np.array([1,2,7,8,np.nan,9,5,np.nan,1,0])
print("this is a sample data with nan valuesin it:",sample_data)
remove_nan=sample_data[np.logical_not(np.isnan(sample_data))]
print(remove_nan)

this is a sample data with nan valuesin it: [ 1.  2.  7.  8. nan  9.  5. nan  1.  0.]
[1. 2. 7. 8. 9. 5. 1. 0.]


In [41]:
#missing values with 0
import numpy as np

#create array of data
my_array = np.array([4, np.nan, 6, np.nan, 10, 11, 14, 19, 22])

#replace nan values with zero in array
my_array[np.isnan(my_array)] = 0

#view updated array
print(my_array)

[ 4.  0.  6.  0. 10. 11. 14. 19. 22.]


In [42]:
x=np.array([1,2,np.nan,3,np.nan,])
y=np.array([[1,2,3],[4,np.nan,5],[np.nan,7,8]])
print("original array:",x )
result = x[np.logical_not(np.isnan(x))]
print("after removing:",result)
result_y=y[np.logical_not(np.isnan(y))]
print("orginal array:",y)
print("after removing nun :",result_y)

original array: [ 1.  2. nan  3. nan]
after removing: [1. 2. 3.]
orginal array: [[ 1.  2.  3.]
 [ 4. nan  5.]
 [nan  7.  8.]]
after removing nun : [1. 2. 3. 4. 5. 7. 8.]


In [43]:
#min by max
arr = np.array([[1,2,33],[4,5,6],[7,8,9]])
print(arr)
min=np.min(arr,axis=1)
max=np.max(arr,axis=1)
minbymax=min/max
print(minbymax)

[[ 1  2 33]
 [ 4  5  6]
 [ 7  8  9]]
[0.03030303 0.66666667 0.77777778]


In [44]:
#normalization
x=np.random.random((3,3))
print("orginal array:",x)
xmax, xmin = x.max(), x.min()
y = (x - xmin) / (xmax - xmin)
print("normalizatio:",y)

orginal array: [[0.6624686  0.34934332 0.21293529]
 [0.05790187 0.47966536 0.11789113]
 [0.17564473 0.92077103 0.88771531]]
normalizatio: [[0.70064704 0.33775856 0.17967198]
 [0.         0.48879193 0.06952301]
 [0.13645505 1.         0.96169093]]
